# Generated by Django 3.2.2 on 2022-07-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('signature_move', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('distance_fr_dt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.IntegerField()),
                ('grade_level', models.IntegerField()),
                ('catch_phrase', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schools')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schools')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersStudents',
            fields=[
                ('user_student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEids',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('pwd_reset_q', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students')),
            ],
        ),
        migrations.CreateModel(
            name='MascotsSchools',
            fields=[
                ('user_school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schools')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.mascots')),
            ],
        ),
    ]
